### ISSUE TITLE
Práctica Architect

### ISSUE THREAD

**Issue by NayeliMoraless** [SistemasTecTlaxiaco/actividad-3-practica-architect-NayeliMoraless#1]
[Practica Architect.pdf](https://github.com/user-attachments/files/16841854/Practica.Architect.pdf)

**Comment by RodolfoNV** [comment]
Recibo de recibo, en base a la rubrica faltan imágenes. 
Calificación 19

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
